### ISSUE TITLE
"CLDR's Property demo" link is broken

### ISSUE THREAD

**Issue by smuehlst** [r12a/uniview#10]
When I select a character in the left-hand display of Unicode characters, on the right-hand side of the web page information about this character appears. The link "CLDR's Property demo" in "More properties at CLDR's Property demo" is broken and results in a "404 Not found" page on unicode.org, e.g.:

http://unicode.org/cldr/utility/character.jsp?a=3099

**Comment by fdavis99** [comment]
Works for me. Maybe that site/service was down on 2020-07-10?

**Comment by smuehlst** [comment]
@fdavis99 Thanks for re-testing. It works for me as well again.
