### ISSUE TITLE
URL query string to display a specified range

### ISSUE THREAD

**Issue by fdavis99** [r12a/uniview#11]
Feature request: a way to copy a link to the current view displaying a custom range, e.g. 0020:007E.
Alternative to a UI feature: document the needed query string in https://r12a.github.io/uniview/help#show_range. I could imagine it looking like:
https://r12a.github.io/uniview/?range=0020:007E

Thanks!

**Comment by r12a** [comment]
@fdavis99 Sorry it took so long.  This should now work.  Thanks for the suggestion.
