### ISSUE TITLE
Uniview's top navigation links have incorrect URLs

### ISSUE THREAD

**Issue by jwakely** [r12a/uniview#14]
At https://r12a.github.io/uniview/index.html the "[blog](https://r12a.github.io/r12a.github.io/blog/index.html)  [docs](https://r12a.github.io/r12a.github.io/doclist.html)  [maps](https://r12a.github.io/r12a.github.io/maplist.html)  [apps](https://r12a.github.io/r12a.github.io/applist.html)  [photos](https://r12a.github.io/r12a.github.io/photos.html)" navigation links at the top all have the domain name duplicated, e.g. https://r12a.github.io/r12a.github.io/blog/index.html

As a result, they all redirect to https://r12a.github.io instead of going to the blog, docs, etc. as presumably intended.

In [the source](https://github.com/r12a/uniview/blob/5db5ac3091d4046d05756149479e59396aa01a5f/index.html#L25) the links use relative paths but include the domain name which seems odd, e.g.  `<a href="../r12a.github.io/blog/index.html">blog</a>`. Maybe that was supposed to be `//r12a.github.io/blog/index.html`?

**Comment by r12a** [comment]
Many thanks for reporting this. I seem to have lost sight of it, but just fixed it now.

The source code was an attempt to make the links work both from my hard drive and from the server.  I'm surprised i didn't test that change properly.  Now it doesn't work when reading files from the hard drive, but it's more important to work via the GH server.
