### ISSUE TITLE
Character data doesn't appear anymore on the right side of the page

### ISSUE THREAD

**Issue by smuehlst** [r12a/uniview#15]
In the past details about a character appeared on the right hand side of the page where the default text says "Character data appears here.", after clicking on a character that is displayed on the left side of the page. 

This does no longer work. I tried this with Google Chrome and Microsoft Edge on Windows as well as with Chrome on Android.

**Comment by smuehlst** [comment]
It works sometimes when larger tables are displayed. For example when displaying the range 0020:0021 with two characters, it doesn't work to display the character properties. But for example with the range 0020:00FF it works when clicking into any character in columns 8 through F.

**Comment by Hoolean** [comment]
I have pushed a patch to r12a/shared#4, which appears to fix this and #16 such that the character data section works for all characters belonging to script groups with ISO tags.

The bug still appears in a few other cases:
- Characters in script groups that do not have an ISO tag (e.g. ⇔)
- Characters outside of any script group (e.g. 𛌀)

These probably need a patch on this repo, as they may involve adding new copy :)

**Comment by r12a** [comment]
@smuehlst @Hoolean thanks for reporting this, and sorry it took so long for me to fix it.  Today, as part of other work, i fixed the bug that was preventing ASCII characters showing up on the right panel.

I'll now check the use cases mentioned in the previous comment.

**Comment by r12a** [comment]
> Characters in script groups that do not have an ISO tag (e.g. ⇔)

This seems to work now.

> Characters outside of any script group (e.g. 𛌀)

Yes.  For some time i've been thinking that this needs some attention, not just for this bug, but for a better general handling of such characters.  I'll see if i can do something fairly soon, since i seem to have a little more free time at the moment.

**Comment by r12a** [comment]
I raise a new issue for the non-characters at https://github.com/r12a/uniview/issues/17 so i'll close this issue now.
