### ISSUE TITLE
Display of character data now broken?

### ISSUE THREAD

**Issue by bortzmeyer** [r12a/uniview#16]
Searching a character still works but clicking on it no longer displays the character data. I just see "Character data appears here.

Any time you click on a character in a list or table to the left, detailed information and links for that character are displayed here."

Tested with Chrome and Firefox.

**Comment by r12a** [comment]
@bortzmeyer thanks for reporting.  Sorry it took so long to get to it, but i made some other changes today that led me to fix it (i think).  I had created a new function from an old one, but forgot to change that line, so ASCII characters were affected.  Should be ok now.

**Comment by bortzmeyer** [comment]
>  Should be ok now.

Indeed, it works. Working without Uniview was painful during this time. Thanks for fixing it.
