### ISSUE TITLE
gif from decodeunicode can no longer be displayed

### ISSUE THREAD

**Issue by tatamu-fold** [r12a/uniview#2]
Seems that they have changed their data format into svg. I feel like it's a bit difficult to extract the svg data from their website. Maybe you can consider using http://www.fileformat.info to replace that.
Examples are 
http://www.fileformat.info/info/unicode/char/5b57/sample.svg
http://www.fileformat.info/info/unicode/char/5b57/sample.png

**Comment by r12a** [comment]
This release https://github.com/r12a/uniview/commit/78035de133041226929cd313031be40e2984a6e2 decouples UniView completely from decodeUnicode.  UniView's now provides images of its own for all Unicode characters, except for Han, Hangul and Tangut. UniView no longer relies on any graphics from decodeUnicode. Han, Hangul and Tangut characters are now always displayed as text (and users are advised to download the free fonts from Babelstone to show the characters.)

Thanks for raising the issue. Sorry it took so long to address it.

**Comment by tatamu-fold** [comment]
What a coincidence! I was just reviewing all the issues I created when you gave the reply. Thanks for the comment.
