### ISSUE TITLE
Text area insertion point not updating

### ISSUE THREAD

**Issue by bobh0303** [r12a/uniview#3]
On Windows Version 10 (Build 15063), using Chrome version 60.0.3112.101 (Official Build) (64-bit):

I click the Text Area "up arrow" so that clicking in the list/chart area adds characters to the text area. Most of the time, the text insertion point always seems to move to the left edge of the box rather than being after just-entered text.

Example: 
I select the Latin 1 block, click, sequentially, on `A`, `b`, and `c`, then the text area contains `cbA`.
If I then move the insertion point to the right end (after the `A`) and click `d`, `e`, the result is `ecbAd`  (that is, the d got put at the end, but then the insertion point was moved back to the start).

Sometimes it works correctly, but most of the time it doesn't, and I can't figure out what's different. The text area reading direction is left-to-right.  

Doesn't seem to fail on Firefox 54.0.1 (32-bit)

**Comment by bobh0303** [comment]
Should have mentioned: UniView title bar says it is 10.0.0.  

(however I notice the initial screen in the block titled _Character data appears here_ that the help text says
>The app covers Unicode version 9.0.0. 

so I'm not sure what version this really is)

**Comment by r12a** [comment]
@bobh0303 Sorry, i somehow missed this issue. I can confirm the behaviour you report also happens on Chrome on a Mac, but not with Firefox or Safari. That's a nuisance. I'll take a look at it when i get a free moment.

I have fixed the version numbering in the _Character data appears here_ panel. Thanks for pointing  out that omission (now set to v10). See https://github.com/r12a/uniview/commit/4b4ea992ceb1ee6c864c0fe6008657d58fe98b8b

**Comment by r12a** [comment]
Hoping that this has gone away by now.

**Comment by bobh0303** [comment]
Doesn't seem to have gone away on Windows 10.0.19045 Build 19045 with **either** Chrome 114.0.5735.199 or Edge 114.0.1823.82 

Didn't reproduce in Firefox (release or nightly build)

**Comment by r12a** [comment]
Sorry.  I think it should be fixed now.

**Comment by bobh0303** [comment]
Seems to work reliably now! Thanks.

**Comment by r12a** [comment]
Thank you.  Sorry it took so long.
