### ISSUE TITLE
Certain Han characters are displayed as ‘unassigned code point’

### ISSUE THREAD

**Issue by charlotte-buff** [r12a/uniview#4]
The last 48 characters in _CJK Unified Ideographs_ (U+9FBB–U+9FEA), as well as the entirety of _CJK Unified Ideographs Extension F_ (U+2CEB0–U+2EBE0) are not recognized as assigned characters by the tool.

- affected characters in _CJK Unified Ideographs_: 龸 龹 龺 龻 龼 龽 龾 龿 鿀 鿁 鿂 鿃 鿄 鿅 鿆 鿇 鿈 鿉 鿊 鿋 鿌 鿍 鿎 鿏 鿐 鿑 鿒 鿓 鿔 鿕 鿖 鿗 鿘 鿙 鿚 鿛 鿜 鿝 鿞 鿟 鿠 鿡 鿢 鿣 鿤 鿥 鿦 鿧 鿨 鿩 鿪
- start and end of Extension F: 𬺰 𬺱 𬺲 𬺳 𬺴 𬺵 𬺶 𬺷 𬺸 𬺹 ... 𮯗 𮯘 𮯙 𮯚 𮯛 𮯜 𮯝 𮯞 𮯟 𮯠

**Comment by r12a** [comment]
I believe this was fixed by https://github.com/r12a/uniview/commit/9310690f1649998bff9ce1427f752dfc8f2389af

Thanks for reporting, and sorry to take so long to get to it.

**Comment by r12a** [comment]
Just realised that Extension F isn't fixed. Will do it.

**Comment by r12a** [comment]
Fixed in this release https://github.com/r12a/uniview/commit/78035de133041226929cd313031be40e2984a6e2
